### ISSUE TITLE
Support pre-parsed body

### ISSUE THREAD

**Issue by MarcPorciuncula** [hopin-team/twirp-ts#12]
Hey, I'm trying to use `twirp-ts` on Google Cloud Functions.

It seems like a `TwirpServer`'s `httpHandler` doesn't work when the http body has already been parsed. 

This is the case when using Cloud Functions, as Cloud Functions will parse the body and place the result on the request as `req.body` before calling the http handler that we provide (in this case the handler returned from the `httpHandler` method on a `TwirpServer`). There's no way to disable this feature.

It would be great if either `getRequestData` handled pre-parsed body data or if there was some way to replace/modify how `getRequestData` works. Would be happy to open a PR if you are interested.

I managed to get a twirp-ts server working on Cloud Functions by patching the following code into `getRequestData`, so something similar would work.

```javascript
function getRequestData(req) {
    return new Promise((resolve, reject) => {
        if (req.body && req.headers['content-type'].match(/application\/json/)) {
            // GCF will parse application/json as in JSON.parse
            resolve(Buffer.from(JSON.stringify(req.body)))
            return
        } else if (req.body && req.headers['content-type'].match(/application\/protobuf/)) {
            // GCF will parse application/protobuf into a Buffer
            resolve(req.body)
            return
        }

        const chunks = [];
        req.on('data', chunk => chunks.push(chunk));
		// ... and so on
```

**Comment by fenos** [comment]
Hi, I'm back from holiday.

Thanks for reporting this issue, is seems a legit request.

As far as I know google cloud functions provides the `req.rawBody` which gives you a buffer out of the box.

However, I'm also thinking that we could allow a `user` function to return the `Buffer` similarly to how you are doing it, for more complex use cases.

Ex:

```ts
const server = createHeberdashServer(...);

server.parseData((req): Buffer | Promise<Buffer> => {
  return req.rawBody
})
```

However I think that I'll support the `rawBody` property by default, so if you request object has it and it is a Buffer it will use that instead.

**Comment by MarcPorciuncula** [comment]
Sounds like `rawBody` will solve the problem just fine, thanks for that!

**Comment by fenos** [comment]
@MarcPorciuncula sorry for the delay, this is now support in `v2.1.3` thanks for reporting!
