### ISSUE TITLE
empty package cause bad behavior

### ISSUE THREAD

**Issue by f0mster** [hopin-team/twirp-ts#24]
According to twirp's specification ( https://twitchtv.github.io/twirp/docs/spec_v7.html ), if the "package" field in a proto file is empty - the prefix must be omited.
But for now,  instead of omitting twirp-ts use "undefined." as a prefix.

**Comment by fenos** [comment]
Thanks for reporting this, will check and send a fix

**Comment by fenos** [comment]
Released in 2.3.6
