### ISSUE TITLE
camel case convention over pascal case for method names

### ISSUE THREAD

**Issue by longility** [hopin-team/twirp-ts#37]
With js/ts, I believe it is more native or natural for method names to be camel case. Unfortunately, that will be a breaking change. However, is that something that have been considered?

Actual:
```typescript
// removed for brevity
const server = createHaberdasherServer({
    async MakeHat(ctx, request): Promise<Hat> {
        return Hat.fromJson({
            name: "cup",
            inches: request.inches,
            color: "blue",
        });
    },
    async FindHat(ctx, request): Promise<FindHatRPC> {
        return request;
    },
    async ListHat(ctx, request): Promise<ListHatRPC> {
        return request;
    }
})

// removed for brevity

app.listen(8000, async () => {
    const jsonResp = await jsonClient.MakeHat({
        inches: 2,
    });

    // removed for brevity

    const protobufResp = await protobufClient.MakeHat({
        inches: 1,
    });

    // removed for brevity
})
```
Expected:
```typescript
// removed for brevity
const server = createHaberdasherServer({
    async makeHat(ctx, request): Promise<Hat> {
        return Hat.fromJson({
            name: "cup",
            inches: request.inches,
            color: "blue",
        });
    },
    async findHat(ctx, request): Promise<FindHatRPC> {
        return request;
    },
    async listHat(ctx, request): Promise<ListHatRPC> {
        return request;
    }
})

// removed for brevity

app.listen(8000, async () => {
    const jsonResp = await jsonClient.makeHat({
        inches: 2,
    });

    // removed for brevity

    const protobufResp = await protobufClient.makeHat({
        inches: 1,
    });

    // removed for brevity
})
```

**Comment by fenos** [comment]
Hello,

Happy to consider adding a flag to the proto generator to force camel-case and keep backwards compatibility.

ex: `--twirp_ts_camelcase`

**Comment by longility** [comment]
I think that should work. I think that should work with buf build too. Correct me if I’m wrong. Is that something you can easily and quickly do? If not, can you guide me as I’m not familiar such as which files I would be touching, etc?

**Comment by fenos** [comment]
@longility yes, it will work with buf build too, it's a standard flag.

It should be fairly quick to add, however, i might need 1 or 2 days before i have sometime to look into this.

If you want to give it a go, here is what you need to change:

- Add the [flag here](https://github.com/hopin-team/twirp-ts/blob/main/src/protoc-gen-twirp-ts/plugin.ts#L21)
- add [a property to the context](https://github.com/hopin-team/twirp-ts/blob/main/src/protoc-gen-twirp-ts/gen/twirp.ts) called `camelCase` which is the value of the flag 
- [Modify all the occurrence ](https://github.com/hopin-team/twirp-ts/blob/main/src/protoc-gen-twirp-ts/gen/twirp.ts) of `method.name` with something like `formatName(method.name, { camelCase: ctx.camelCase })`

**Comment by longility** [comment]
I will see if I can do this in 30 min

**Comment by longility** [comment]
@fenos I did not test, but followed your instructions. Feel free to take over from here or do own implementation if I'm not doing it in a way that fits the patterns since it was easy enough.
