### ISSUE TITLE
Support 

### ISSUE THREAD

**Issue by delaneyj** [hopin-team/twirp-ts#6]
[Auto-Batching / N+1 Prevention](https://github.com/stephenh/ts-proto#auto-batching--n1-prevention) support relies on `useContext=true` in protobuf generation.  If you use that setting twirp-ts errors out on generation.

**Comment by fenos** [comment]
Hello, I just tried to run this command with batch enabled:

```bash

PROTOC_GEN_TWIRP_BIN="./node_modules/.bin/protoc-gen-twirp_ts"
PROTOC_GEN_TS_PROTO_BIN="./node_modules/.bin/protoc-gen-ts_proto"

OUT_DIR="./generated"

protoc \
-I ./protos \
--plugin=protoc-gen-ts=$(PROTOC_GEN_TS_PROTO_BIN) \
--plugin=protoc-gen-twirp_ts=$(PROTOC_GEN_TWIRP_BIN) \
--ts_proto_opt=esModuleInterop=true \
--ts_proto_opt=useContext=true \
--ts_proto_out=$(OUT_DIR) \
--twirp_ts_out=$(OUT_DIR) \
./protos/*.proto
```

on this [Proto File](https://github.com/stephenh/ts-proto/blob/main/integration/batching/batching.proto) and it worked just fine

can you please paste the error, the command and the proto you are having issue with

**Comment by delaneyj** [comment]
I had done a `ts_proto_out` not a `ts_proto_opt` sorry about that
